---
services: docker

env:
# CentOS 7
  - distro: centos
    distro_version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ansible_version: "1.9.6"
  - distro: centos
    distro_version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ansible_version: "2.0.2"
  - distro: centos
    distro_version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ansible_version: "2.1.3"
  - distro: centos
    distro_version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ansible_version: "2.2.0"
# CentOS 6
  - distro: centos
    distro_version: 6
    init: /sbin/init
    run_opts: ""
    ansible_version: "2.2.0"
# Debian 7
  - distro: debian
    distro_version: 7
    init: /sbin/init
    run_opts: ""
    ansible_version: "2.2.0"
# Debian 8
  - distro: debian
    distro_version: 8
    init: /sbin/init
    run_opts: ""
    ansible_version: "2.2.0"
# Ubuntu 14.04
  - distro: ubuntu
    distro_version: 14.04
    init: /sbin/init
    run_opts: ""
    ansible_version: "2.2.0"
# Ubuntu 16.04
  - distro: ubuntu
    distro_version: 16.04
    init: "/lib/systemd/systemd"
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    ansible_version: "2.2.0"

before_install:
  # Pull container.
  - 'docker pull ${distro}:${distro_version}'

script:
  - /bin/bash "${PWD}/tests/docker.sh" "${distro}" "${distro_version}" "${init}" "${run_opts}" "${ansible_version}" "${PWD}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
